### ISSUE TITLE
Doesn't show anything, no errors

### ISSUE THREAD

**Issue by vlakarados** [jbrooksuk/Intellitip#16]
Sublime Text 3 Build 3084, KUbuntu Linux 14.04.
Installed packages:

+ CodeComplice
+ DocBlockr
+ Devastate
+ Gist
+ Package Resource Viewer
+ php-grammar
+ SublimeLinter (php, phpmd, phpcs)
+ Sidebar Enchancements
+ Custom PHP definitions.

May it be because of custom PHP language definitions?

**Comment by jbrooksuk** [comment]
I have a custom PHP language file too, but it continues to work. Are there any errors printed in the console?

**Comment by jfcherng** [comment]
FYI.
I download the package from github rather than using package control, and it works.
I notice that the one downloaded from package control seems to be different from github's contents.

**Comment by jbrooksuk** [comment]
It's all tagged up, so Package Control should be the same.

**Comment by jfcherng** [comment]
![2015-05-14_15-17-11](https://cloud.githubusercontent.com/assets/6594915/7627699/8b74ead8-fa4c-11e4-9a22-79ff1eb49e7b.png)

This is what I just get by Package Control with Sublime Text Dev 3086.
It's weird.

**Comment by slifin** [comment]
Can confirm what jfcherng is seeing
